name: test
on:
  push
jobs: 
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.6','3.7','3.8']
      max-parallel: 1
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pytest
          python setup.py install
      - name: Install BATS requiremetns
        run: |      
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core && ./install.sh $HOME && cd ..
          cd tests
          git clone https://github.com/ztombol/bats-support
          git clone https://github.com/ztombol/bats-assert
          cd ..
      - name: Setup msiempy config
        run: python -m msiem config --set esm host ${{ secrets.esmhost }} --set esm user NGCP --set esm passwd ${{ secrets.esmpass }} --set general timeout 60
      - name: Run Python unittests
        run: pytest
      - name: Run BATS test
        run: $HOME/bin/bats ./tests/test.bats
        
